defmodule Moba.Admin.Avatars do
  @moduledoc """
  Admin functions for managing Avatars, mostly generated by Torch package.
  """

  alias Moba.{Repo, Game}
  alias Game.Schema.Avatar
  alias Game.Query.AvatarQuery

  import Ecto.Query, warn: false
  import Torch.Helpers, only: [sort: 1, paginate: 4]
  import Filtrex.Type.Config

  @pagination [page_size: 50]
  @pagination_distance 5

  def paginate(params \\ %{}) do
    params =
      params
      |> Map.put_new("sort_direction", "desc")
      |> Map.put_new("sort_field", "inserted_at")

    {:ok, sort_direction} = Map.fetch(params, "sort_direction")
    {:ok, sort_field} = Map.fetch(params, "sort_field")

    with {:ok, filter} <- Filtrex.parse_params(filter_config(:avatars), params["avatar"] || %{}),
         %Scrivener.Page{} = page <- do_paginate(filter, params) do
      {:ok,
       %{
         avatars: page.entries,
         page_number: page.page_number,
         page_size: page.page_size,
         total_pages: page.total_pages,
         total_entries: page.total_entries,
         distance: @pagination_distance,
         sort_field: sort_field,
         sort_direction: sort_direction
       }}
    else
      {:error, error} -> {:error, error}
      error -> {:error, error}
    end
  end

  def list do
    Repo.all(Avatar)
  end

  def get!(id), do: Repo.get!(Avatar, id)

  def create(attrs \\ %{}) do
    Game.create_avatar!(%Avatar{}, attrs, nil)
  end

  def update(%Avatar{} = avatar, attrs) do
    avatar
    |> Avatar.changeset(attrs)
    |> Repo.update()
  end

  def delete(%Avatar{} = avatar) do
    Repo.delete(avatar)
  end

  def change(%Avatar{} = avatar) do
    Avatar.changeset(avatar, %{})
  end

  defp do_paginate(filter, params) do
    AvatarQuery.canon()
    |> Filtrex.query(filter)
    |> order_by(^sort(params))
    |> paginate(Repo, params, @pagination)
  end

  defp filter_config(:avatars) do
    defconfig do
      boolean(:enabled)
      text(:name)
      text(:code)
      text(:role)
      number(:atk)
      number(:total_hp)
      number(:total_mp)
      number(:atk_per_level)
      number(:hp_per_level)
      number(:mp_per_level)
      number(:speed)
      number(:power)
      number(:armor)
    end
  end
end
